Project backend
Lucas-Angelo/pizzaria pull request #18
Opened 2022-09-23 01:06 UTC by Lucas-Angelo

#1

2022-09-23 03:54 UTC, Lucas-Angelo commented
@Henrikkee Postman collection

```json
{
	"info": {
		"_postman_id": "03dbe03a-d25b-49ff-b05b-901234f71e95",
		"name": "Pizzaria",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "11631363"
	},
	"item": [
		{
			"name": "Usuario",
			"item": [
				{
					"name": "Create",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\r\n    \"email\": \"teste0@teste.com\",\r\n    \"senha\": \"supersenha123\"\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{host}}/api/usuario",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"usuario"
							]
						}
					},
					"response": []
				},
				{
					"name": "Delete by id",
					"request": {
						"method": "DELETE",
						"header": [],
						"url": {
							"raw": "{{host}}/api/usuario/3",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"usuario",
								"3"
							]
						}
					},
					"response": []
				},
				{
					"name": "Update by id",
					"request": {
						"method": "PUT",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\r\n    \"senha\": \"supersenha\"\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{host}}/api/usuario/1",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"usuario",
								"1"
							]
						}
					},
					"response": []
				},
				{
					"name": "Get by id",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "{{host}}/api/usuario/1",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"usuario",
								"1"
							]
						}
					},
					"response": []
				},
				{
					"name": "Get all",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "x-access-token",
								"value": "{{tt}}",
								"type": "text"
							}
						],
						"url": {
							"raw": "{{host}}/api/usuario?pagina=1&limite=5&atributo=email&ordem=DESC",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"usuario"
							],
							"query": [
								{
									"key": "pagina",
									"value": "1"
								},
								{
									"key": "limite",
									"value": "5"
								},
								{
									"key": "atributo",
									"value": "email"
								},
								{
									"key": "ordem",
									"value": "DESC"
								}
							]
						}
					},
					"response": []
				}
			]
		},
		{
			"name": "Pizza",
			"item": [
				{
					"name": "Create",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\r\n    \"descricao\": \"quatro queijos\",\r\n    \"tamanho\": \"35CM\",\r\n    \"image_url\": \"https://i.imgur.com/wOKQA9n.png\"\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{host}}/api/pizza",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pizza"
							]
						}
					},
					"response": []
				},
				{
					"name": "Delete by id",
					"request": {
						"method": "DELETE",
						"header": [],
						"url": {
							"raw": "{{host}}/api/pizza/2",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pizza",
								"2"
							]
						}
					},
					"response": []
				},
				{
					"name": "Update by id",
					"request": {
						"method": "PUT",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\r\n    \"tamanho\": \"60CM\",\r\n    \"image_url\": \"https://i.imgur.com/wOKQA9n.png\"\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{host}}/api/pizza/1",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pizza",
								"1"
							]
						}
					},
					"response": []
				},
				{
					"name": "Get by id",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "{{host}}/api/pizza/1",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pizza",
								"1"
							]
						}
					},
					"response": []
				},
				{
					"name": "Get all",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "x-access-token",
								"value": "{{tt}}",
								"type": "text"
							}
						],
						"url": {
							"raw": "{{host}}/api/pizza?pagina=1&limite=5&atributo=id&ordem=ASC",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pizza"
							],
							"query": [
								{
									"key": "pagina",
									"value": "1"
								},
								{
									"key": "limite",
									"value": "5"
								},
								{
									"key": "atributo",
									"value": "id"
								},
								{
									"key": "ordem",
									"value": "ASC"
								}
							]
						}
					},
					"response": []
				}
			]
		},
		{
			"name": "Pedido",
			"item": [
				{
					"name": "Create",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\r\n    \"valor\": 100,\r\n    \"cliente_nome\": \"Zé\",\r\n    \"pizza_id\": 1\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{host}}/api/pedido",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pedido"
							]
						}
					},
					"response": []
				},
				{
					"name": "Delete by id",
					"request": {
						"method": "DELETE",
						"header": [],
						"url": {
							"raw": "{{host}}/api/pedido/2",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pedido",
								"2"
							]
						}
					},
					"response": []
				},
				{
					"name": "Update by id",
					"request": {
						"method": "PUT",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\r\n    \"status\": \"PRODUCAO\",\r\n    \"valor\": 101,\r\n    \"cliente_nome\": \"Zé\"\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{host}}/api/pedido/1",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pedido",
								"1"
							]
						}
					},
					"response": []
				},
				{
					"name": "Get by id",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "{{host}}/api/pedido/1",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pedido",
								"1"
							]
						}
					},
					"response": []
				},
				{
					"name": "Get all",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "x-access-token",
								"value": "{{tt}}",
								"type": "text"
							}
						],
						"url": {
							"raw": "{{host}}/api/pedido?pagina=1&limite=5&atributo=id&ordem=ASC",
							"host": [
								"{{host}}"
							],
							"path": [
								"api",
								"pedido"
							],
							"query": [
								{
									"key": "pagina",
									"value": "1"
								},
								{
									"key": "limite",
									"value": "5"
								},
								{
									"key": "atributo",
									"value": "id"
								},
								{
									"key": "ordem",
									"value": "ASC"
								}
							]
						}
					},
					"response": []
				}
			]
		}
	],
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"variable": [
		{
			"key": "h [...]

2022-09-23 14:05 UTC, lucaspere requested changes

2022-09-23 14:05 UTC, lucaspere commented on src/backend/models/Pedido.js
> +
Use o [hook](https://sequelize.org/docs/v6/other-topics/hooks/) aqui para evitar que no **Controller** atribua o ***status***.

```javascript
Pedido.beforeCreate((pedido, options) => {
  pedido.status = "PENDENTE";
});
```

2022-09-23 14:05 UTC, lucaspere commented on src/backend/controllers/PedidoController.js
> +        );
Com o hook, não vai precisar definir isto aqui. Observar a comentário no **models/Pedido.js**

2022-09-23 14:05 UTC, lucaspere commented on src/backend/services/PedidoService.js
> +module.exports = PedidoService;
Como a classe não tem nenhum *state*, isto é, nenhum atributo (ela é somente uma coleção de métodos), podemos usar o **Singleton** aqui para deixar como instância global.

```javascript
module.exports = new PedidoService();
```

Dessa forma, os consumidores dessa classe não vai precisar dar um ``new`` toda hora.

2022-09-23 14:05 UTC, lucaspere commented on src/backend/services/PizzaService.js
> +module.exports = PizzaService;
O mesmo que encima.

2022-09-23 14:05 UTC, lucaspere commented on src/backend/services/UsuarioService.js
> +module.exports = UsuarioService;
O mesmo que encima.

2022-09-23 14:05 UTC, lucaspere commented on src/backend/services/PizzaService.js
> +            ]);
Não entendi, se a descrição da pizza tem que ser única, porquê não deixa ela como PK? E também, não vi nenhuma validação restrita sobre esse atributo.

Por exemplo, se usuário criar uma pizza com descrição **Pizza de Calabresa** e outro usuário mandar criar uma pizza com descrição **Pizza de calabresa**, a gente vai ter duas pizzas com praticamente com a mesma descrição, né?

2022-09-23 14:05 UTC, lucaspere commented on src/backend/services/PedidoService.js
> +        });
Usa o método [findByPK](https://sequelize.org/api/v6/class/src/model.js~model#static-method-findByPk)

```javascript
const pedido = await Pedido.findByPk(id, attributes)

2022-09-23 14:05 UTC, lucaspere commented on src/backend/services/PedidoService.js
> +        }).catch((error) => {
O mesmo de cima

2022-09-23 14:05 UTC, lucaspere commented on src/backend/services/PizzaService.js
> +        }).catch((error) => {
O mesmo de cima

2022-09-25 19:19 UTC, Henrikkee commented
![image](https://user-images.githubusercontent.com/24460777/192161366-b3103f20-cf79-4283-9c54-55bd8005e267.png)
Campo "valor" está retornando como string

2022-09-25 19:19 UTC, Henrikkee requested changes
![image](https://user-images.githubusercontent.com/24460777/192161366-b3103f20-cf79-4283-9c54-55bd8005e267.png)
Campo "valor" está retornando como string

2022-09-25 20:02 UTC, Henrikkee approved these changes

2022-09-26 12:00 UTC, merged