criação de um novo campo
Lucas-Angelo/pizzaria pull request #38
Opened 2022-10-02 02:30 UTC by viniciusalvessantos

foi  adicionado um novo  campo do tipo enum 
para diferenciar os pedidos

2022-10-02 02:49 UTC, Lucas-Angelo commented
@viniciusalvessantos The database script is also here: https://github.com/Lucas-Angelo/pizzaria/blob/main/src/database/DatabaseScript.sql

2022-10-02 02:53 UTC, 777-victor requested changes
No create/update do pedido ( pedidoService ) ta faltando o tipo 

![image](https://user-images.githubusercontent.com/59877368/193435777-4219067a-7097-4e00-b28b-029f84f566d6.png)



E você pode remover essa parte grifada:

![image](https://user-images.githubusercontent.com/59877368/193435450-303f029f-ec4e-40a5-ad79-888f823f2051.png)

2022-10-03 00:33 UTC, 777-victor approved these changes

2022-10-03 01:39 UTC, Lucas-Angelo approved these changes

2022-10-03 01:41 UTC, merged