feat: add filter to getAll Pizza
Lucas-Angelo/pizzaria pull request #62
Opened 2022-10-17 11:33 UTC by lucaspere

This PR adds a filter to ``getAll`` in ``Pizza`` model.

#### Changelog

- Creates ``buildLikeFilter``, ``buildValorFilter`` and ``buildWhere`` pizza helpers;
- Refactor the ``getAll``.

2022-10-17 11:47 UTC, Lucas-Angelo commented
@lucaspere can you add postman collection with request and filters for Pizza? Or, cURL. For me to test

2022-10-18 10:36 UTC, Lucas-Angelo approved these changes

2022-10-18 15:40 UTC, guizombas requested changes

2022-10-18 15:40 UTC, guizombas commented on src/backend/services/PizzaService.js
> +const { SortPaginate, buildWhere } = require("../helpers/SortPaginate");
buildWhere is being imported from the wrong file

2022-10-18 15:40 UTC, guizombas commented on src/backend/helpers/pizza.js
> +            typeof value == "number"
will this work? as the value comes from the query string, won't it be of type "string" for every case ?

2022-10-18 17:32 UTC, lucaspere commented on src/backend/services/PizzaService.js
> +const { SortPaginate, buildWhere } = require("../helpers/SortPaginate");
Good catch!

2022-10-18 18:46 UTC, guizombas requested changes
getting an error when trying using the 'valor_maior_que' or 'valor_menor_que' filter, because it's not a valid filed name. 

![image](https://user-images.githubusercontent.com/63319368/196516206-83d497e0-a958-4a06-92a4-fd098bb5c075.png)

```
http://localhost:3001/api/pizza?valor_maior_que=9

response:

{
  "message": "Erro interno do servidor!",
  "error": {
    "name": "SequelizeDatabaseError",
    "parent": {
      "code": "ER_BAD_FIELD_ERROR",
      "errno": 1054,
      "sqlState": "42S22",
      "sqlMessage": "Unknown column 'Pizza.valor_maior_que' in 'where clause'",
      "sql": "SELECT count(*) AS `count` FROM `pizza` AS `Pizza` WHERE `Pizza`.`valor_maior_que` >= '9' AND `Pizza`.`updated_at` BETWEEN '1970-01-01 00:00:00' AND '2022-10-18 18:39:25' AND `Pizza`.`created_at` BETWEEN '1970-01-01 00:00:00' AND '2022-10-18 18:39:25';"
    },
    "original": {
      "code": "ER_BAD_FIELD_ERROR",
      "errno": 1054,
      "sqlState": "42S22",
      "sqlMessage": "Unknown column 'Pizza.valor_maior_que' in 'where clause'",
      "sql": "SELECT count(*) AS `count` FROM `pizza` AS `Pizza` WHERE `Pizza`.`valor_maior_que` >= '9' AND `Pizza`.`updated_at` BETWEEN '1970-01-01 00:00:00' AND '2022-10-18 18:39:25' AND `Pizza`.`created_at` BETWEEN '1970-01-01 00:00:00' AND '2022-10-18 18:39:25';"
    },
    "sql": "SELECT count(*) AS `count` FROM `pizza` AS `Pizza` WHERE `Pizza`.`valor_maior_que` >= '9' AND `Pizza`.`updated_at` BETWEEN '1970-01-01 00:00:00' AND '2022-10-18 18:39:25' AND `Pizza`.`created_at` BETWEEN '1970-01-01 00:00:00' AND '2022-10-18 18:39:25';",
    "parameters": {
      
    }
  }
}
```

this bug also happens when you pass any other query string parametter, like 'order' and 'atribute', required for sorting the data: 

![image](https://user-images.githubusercontent.com/63319368/196517609-a25565bf-8453-41ab-9c2a-b8dfc03d0bcb.png)

2022-10-18 22:12 UTC, guizombas approved these changes

2022-10-18 22:13 UTC, merged